services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: cepas-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle123
      - APP_USER=cepas
      - APP_USER_PASSWORD=cepas123
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./recursos:/opt/oracle/scripts/setup
    restart: always
    networks:
      - cepas-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: cepas-backend
    ports:
      - "3001:3001"
    environment:
      - TNS_ADMIN=/usr/src/app/wallet
      - NODE_ENV=production
    depends_on:
      - oracle
    restart: always
    networks:
      - cepas-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: cepas-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001/api
    depends_on:
      - backend
    restart: always
    networks:
      - cepas-network

volumes:
  oracle_data:

networks:
  cepas-network:
    driver: bridge
