services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: cepas-backend
    ports:
      - "3001:3001"
    environment:
      - TNS_ADMIN=/usr/src/app/wallet
    restart: always
    networks:
      - cepas-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: cepas-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    # >>> MUDANÇA AQUI: Adicionando a variável para compatibilidade com cepasService.js <<<
    environment:
      - REACT_APP_API_BASE_URL=http://backend:3001/api
    # >>> FIM DA MUDANÇA <<<
    restart: always
    networks:
      - cepas-network

networks:
  cepas-network:
    driver: bridge
