services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: cepas-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle123
      - APP_USER=cepas
      - APP_USER_PASSWORD=cepas123
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./recursos:/opt/oracle/scripts/setup
    restart: always
    networks:
      - cepas-network
    # OTIMIZADO PARA 1GB RAM - Limites de memória
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: cepas-backend
    ports:
      - "3001:3001"
    environment:
      - TNS_ADMIN=/usr/src/app/wallet
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=200
      - DB_POOL_MIN=1
      - DB_POOL_MAX=3
      - DB_POOL_TIMEOUT=30
    depends_on:
      - oracle
    restart: always
    networks:
      - cepas-network
    # OTIMIZADO PARA 1GB RAM - Limites de memória
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.3

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: cepas-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001/api
    depends_on:
      - backend
    restart: always
    networks:
      - cepas-network
    # OTIMIZADO PARA 1GB RAM - Limites de memória
    mem_limit: 128m
    mem_reservation: 64m
    cpus: 0.2

volumes:
  oracle_data:

networks:
  cepas-network:
    driver: bridge
